### ISSUE TITLE
Can you create a release to reflect the saloonphp update?

### ISSUE THREAD

**Issue by joshembling** [probots-io/pinecone-php#8]
As saloon has moved to `saloonphp`, can you create a release to reflect the commit from last year, please? 

Gets rid of both of these warnings:
```bash
Package sammyjo20/saloon is abandoned, you should avoid using it. Use saloonphp/saloon instead.

Class Probots\Pinecone\Requests\Exceptions\MissingNameException located in ./vendor/probots-io/pinecone-php/src/Exceptions/MissingNameException.php does not comply with psr-4 autoloading standard. Skipping.
```

P.S - thanks for a great package!

**Comment by sedwardsgt** [comment]
Yes, please. We ended up having to fork this and create our own release just so we could deploy it with Laravel 10s [suggestion](https://laravel.com/docs/10.x/upgrade#updating-minimum-stability) to set `minimum-stability: stable`

**Comment by joshembling** [comment]
@derpoho Sorry to prod you on this, not sure if you have seen it?

**Comment by derpoho** [comment]
Sorry guys. Been busy. Release created. See here: https://github.com/probots-io/pinecone-php/releases/tag/0.1.0
